### ISSUE TITLE
getSij function seems to be wrong

### ISSUE THREAD

**Issue by deepakrajendraprasad** [srhariha/SpatioTemporalSEIR#1]
@srhariha 

[File](src/cMatrixComputation.ipynb)

I'm not sure about the getSij function implementation in It looks like you are taking all the regions which are closer to i than j. What we need is all the regions closer to i than d(i,j). Think of a circle centered at Ri of radius d(R1,R2) and include all the regions in that circle.

**Comment by srhariha** [comment]
I see. I misunderstood. 

What is d(R1,R2)? Is it distance between R1 and R2?

Sij equation is not very clear to me. Both the math formula and its implication. Can you explain using the sample set example given in https://github.com/srhariha/SpatioTemporalSEIR/blob/master/src/cMatrixComputation.ipynb

**Comment by srhariha** [comment]
This is what the doc says.

> Si,j is the total population in all the regions (except Ri itself) which are closer to Ri than Rj

I took "all" literally all regions in R

**Comment by deepakrajendraprasad** [comment]
Resolved it over a call
